### ISSUE TITLE
Production: Set up Spring profiles and change ports

### ISSUE THREAD

**Issue by akelsch** [akelsch/spring-reactive-chat#10]
Am besten machen wir das wie hier: https://github.com/jonashackt/spring-boot-vuejs

D.h. Vue auf 8080, Spring auf 8088 (auf 8081 läuft schon Jenkins)

Dann brauchen wir auch noch ein prod profile dass uns SSL anschaltet (#6) aber lokal zum testen aus lässt.

**Comment by LeslieM98** [comment]
Sagt bescheid sobald die Ports geändert sind, ich muss dann was an der Buildchain ändern sonst deployed der nicht ganz Richtig.
